x_league_app/config/routes.rb
Rails.application.routes.draw do
  root 'users#index'
  resources :users, only: [:new, :create]

  resources :games
  resources :players
  resources :performances
  resources :teams, shallow: true do
    resources :players
  end
  resources :games do
    resources :players, only: [:index] do
      resources :performances
    end
  end
  resources :players do
    resources :games, only: [:index]
  end
  resources :sessions, only: [:new, :create, :destroy]
  get '/login', to: 'sessions#new'
  get '/logout', to: 'sessions#destroy'

  get '/favorite/:id/pick', to: 'players#pick_favorite', as: "pick_favorite"
  get '/favorite/:id', to: 'players#favorite', as: "favorite"

end

x_league_app/app/models/game.rb
class Game < ActiveRecord::Base
  has_many :performances
  has_many :players, through: :performances
  belongs_to :home_team, class_name: "Team", foreign_key: "home_id"
  belongs_to :away_team, class_name: "Team", foreign_key: "away_id"
  # has_and_belongs_to_many :players


end

x_league_app/app/models/performance.rb
class Performance < ActiveRecord::Base
  belongs_to :player
  belongs_to :game
end

x_league_app/app/models/player.rb
class Player < ActiveRecord::Base
  belongs_to :team
  has_many :performances
  has_many :games, through: :performances
  # has_and_belongs_to_many :games

end

x_league_app/app/models/team.rb
class Team < ActiveRecord::Base
  has_many :games
  has_many :players

  def games
    Game.where("home_id=" + self.id.to_s + " OR away_id=" + self.id.to_s)
  end

  def home_games
    Game.where(home_team: self.id)
  end

  def away_games
    Game.where(away_team: self.id)
  end

  def self.byob
    where(name: "B.Y.O.B")
  end

  def to_param
    "#{id}-#{name.parameterize}"
  end
end

x_league_app/app/models/user.rb
class User < ActiveRecord::Base
  after_initialize :set_default_values

  def set_default_values
    self.admin ||= false
  end

  has_secure_password
  validates :email, presence: true, uniqueness: true, on: :create
  validates :password, :length => {:minimum => 6}, on: :create
end

x_league_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  def authorize
      redirect_to login_path, alert: 'Not authorized - you must be logged in!' if current_user.nil?
  end

  def admin_authorize
      redirect_to login_path, alert: 'Not authorized - you must be an admin!' unless current_user && current_user.admin
  end

  private
    helper_method :current_user

    def current_user
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end
end

x_league_app/app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :admin_authorize, only: [:new, :edit]

  def new
    @game = Game.new
    # @teams = Team.order(:name)
  end

  def create
    @game = Game.new(params.require(:game).permit(:game_number, :date, :home_id, :home_points, :away_id, :away_points))

    if @game.save
      flash[:notice] = "You have successfully created a game!"
      redirect_to games_path
    else
      render:new
    end
  end

  def index
    @games = Game.all
    @players = Player.all
    @performances = Performance.all
    @teams = Team.all
  end

  def edit
    @game = Game.find(params[:id])
  end

  def update
    @game = Game.find(params[:id])

    if @game.update_attributes(params.require(:game).permit(:name, :division))
      redirect_to edit_game_path(@game.id)
    else
      render :edit
    end
  end

  def show
    @game = Game.find(params[:id])
  end

  def destroy
    @game = Game.find(params[:id])
    @game.performances.each do |p|
      p.destroy
    end
    @game.destroy
    flash[:notice] = "You have successfully deleted a game!"
    redirect_to games_path
  end

end

x_league_app/app/controllers/performances_controller.rb
class PerformancesController < ApplicationController
  before_action :admin_authorize, only: [:new, :edit]

  def new
    @performance = Performance.new
  end

  def create
    @performance = Performance.new(params.require(:performance).permit(:player_id, :game_id, :pts, :fgm, :fga, :tpm, :tpa, :ftm, :fta, :reb, :ast, :stl, :blk))

    if @performance.save
      flash[:notice] = "You have successfully created a performance!"
      redirect_to performances_path
    else
      render :new
    end
  end

  def show
    @performance = Performance.find(params[:id])
  end

  def edit
    @performance = Performance.find(params[:id])
  end

  def update
    @performance = Performance.find(params[:id])

    if @performance.update_attributes(params.require(:performance).permit(:pts, :fgm, :fga, :tpm, :tpa, :ftm, :fta, :reb, :ast, :stl, :blk))
      redirect_to edit_performance_path(@performance.id)
    else
      render :edit
    end
  end

  def destroy
    @performance = Performance.find(params[:id])
    @performance.destroy
    flash[:notice] = "You have successfully deleted a performance!"
    redirect_to performances_path
  end
end

x_league_app/app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :admin_authorize, only: [:new, :edit]

  def show
    @player = Player.find(params[:id])
  end

  def index
    @teams = Team.all
  end

  def edit
    @player = Player.find(params[:id])
  end

  def update
    @player = Player.find(params[:id])

    if @player.update_attributes(params.require(:player).permit(:name, :player_number))
      redirect_to edit_player_path(@player.id)
    else
      render :edit
    end
  end

  def destroy
    @player = Player.find(params[:id])
    @player.performances.each do |p|
      p.delete
    end
    @player.destroy
    flash[:notice] = "You have successfully deleted a player!"
    redirect_to players_path
  end

  def favorite
    @player = Player.find(params[:id])
  end

  def new
    @player = Player.new
  end

  def create
    @player = Player.new(params.require(:player).permit(:name, :player_number, :team_id))
    if @player.save
      redirect_to players_path
    else
      render :new
    end
  end

  def pick_favorite
    current_user.update_attributes(favorite: params[:id])
    redirect_to favorite_path(params[:id])
  end
end

x_league_app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password]) && user.admin
      session[:user_id] = user.id
        if current_user.favorite
          redirect_to favorite_path(current_user.favorite)
        else
          redirect_to root_path
        end
    elsif user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:notice] = 'Logged in!'
      redirect_to root_path
    else
      flash.now.alert = 'Invalid login credentials - try again!'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

x_league_app/app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :admin_authorize, only: [:new, :edit]

  def new
    @team = Team.new
  end

  def create
    @team = Team.new(params.require(:team).permit(:name, :division))

    if @team.save
      redirect_to teams_path
    else
      render :new
    end
  end

  def show
    @team = Team.find(params[:id])
  end

  def edit
    @team = Team.find(params[:id])
  end

  def update
    @team = Team.find(params[:id])

    if @team.update_attributes(params.require(:team).permit(:name, :division))
      redirect_to edit_team_path(@team.id)
    else
      render :edit
    end
  end

  def index
    @teams = Team.all
  end
end

x_league_app/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render 'new'
    end
  end

  private
    # Implement Strong Params
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

x_league_app/app/helpers/application_helper.rb
module ApplicationHelper
end

x_league_app/app/helpers/games_helper.rb
module GamesHelper
end

x_league_app/app/helpers/performances_helper.rb
module PerformancesHelper
end

x_league_app/app/helpers/players_helper.rb
module PlayersHelper
end

x_league_app/app/helpers/sessions_helper.rb
module SessionsHelper
end

x_league_app/app/helpers/teams_helper.rb
module TeamsHelper
end

x_league_app/app/helpers/users_helper.rb
module UsersHelper
end

x_league_app/app/views/performances/index.html.erb
  <% if flash[:notice] %>
    <div class="notice"><%= flash[:notice] %></div>
  <% end %>

x_league_app/app/views/players/edit.html.erb
<h1>Edit <%= link_to @player.name, player_path %></h1>

<%= form_for @player, :html => {:class => "form-horizontal center"} do |f| %>

    <div class="form-group">
        <div class="col-md-8">
        <%= f.label :name %>
        <br>
        <%= f.text_field :name, class: "col-md-4" %>
    </div>
    </div>

    <div class="form-group">
        <div class="col-md-8">
        <%= f.label :player_number %>
        <br>
        <%= f.text_field :player_number, class: "col-md-4" %>
    </div>
    </div>

  <div class="form-group">
    <div class="col-md-8">
        <%= f.label :team_id %>
        <br>
        <%= f.collection_select :team_id, Team.order(:name), :id, :name, include_blank: true, class: "col-md-4" %>
    </div>
    </div>

    <%= f.submit "Submit changes" %>

<% end %>

x_league_app/app/views/players/favorite.html.erb
<% if current_user && current_user.admin %>
  <h4>
  <%= link_to "Create a Team", new_team_path %> ||
  <%= link_to "Create a Player", new_player_path %> ||
  <%= link_to "Create a Game", new_game_path %> ||
  <%= link_to "Create a Performance", new_performance_path %>
  </h4>
<% end %>

<h1>Your Player: <%= @player.name %></h1>

  <h2>Game Stats</h2>
    <table class="table table-hover table-condensed table-bordered">
      <thead>
        <tr class="active">
          <th>Date</th>
          <th>Opponent</th>
          <th>PTS</th>
          <th>FGM-FGA</th>
          <th>3PM-3PA</th>
          <th>FTM-FTA</th>
          <th>REB</th>
          <th>AST</th>
          <th>STL</th>
          <th>BLK</th>
        </tr>
      </thead>

    <% @total_pts = 0 %>
    <% @total_fgm = 0 %>
    <% @total_fga = 0 %>
    <% @total_tpm = 0 %>
    <% @total_tpa = 0 %>
    <% @total_ftm = 0 %>
    <% @total_fta = 0 %>
    <% @total_reb = 0 %>
    <% @total_ast = 0 %>
    <% @total_stl = 0 %>
    <% @total_blk = 0 %>

  <% @performances = @player.performances %>
  <% @performances = @performances.sort_by {|p| p.game.date} %>
  <% @performances.each do |performance| %>

      <tr>
        <td><%= performance.game.date.strftime("%m/%d/%Y") %></td>
        <td>
          <%= if performance.game.home_id == @player.team_id
          then Team.find_by(id: performance.game.away_id).name
          else Team.find_by(id: performance.game.home_id).name end %>
        </td>
        <td><%= performance.pts %></td>
        <td><%= performance.fgm %>-<%= performance.fga %></td>
        <td><%= performance.tpm %>-<%= performance.tpa %></td>
        <td><%= performance.ftm %>-<%= performance.fta %></td>
        <td><%= performance.reb %></td>
        <td><%= performance.ast %></td>
        <td><%= performance.stl %></td>
        <td><%= performance.blk %></td>
        <% @total_pts += performance.pts %>
        <% @total_fgm += performance.fgm %><% @total_fga += performance.fga %>
        <% @total_tpm += performance.tpm %><% @total_tpa += performance.tpa %>
        <% @total_ftm += performance.ftm %><% @total_fta += performance.fta %>
        <% @total_reb += performance.reb %>
        <% @total_ast += performance.ast %>
        <% @total_stl += performance.stl %>
        <% @total_blk += performance.blk %>
      </tr>
    <% end %>

    <thead class="active">
      <th>Totals</th>
      <th>-</th>
      <th><%= @total_pts %></th>
      <th><%= @total_fgm %>-<%= @total_fga %></th>
      <th><%= @total_tpm %>-<%= @total_tpa %></th>
      <th><%= @total_ftm %>-<%= @total_fta %></th>
      <th><%= @total_reb %></th>
      <th><%= @total_ast %></th>
      <th><%= @total_stl %></th>
      <th><%= @total_blk %></th>
    </thead>

    </table>

  <h2>Games</h2>

<% @games = @player.games %>
<% @games = @games.sort_by {|h| h[:date]} %>
<% @games.each do |game| %>

  <h3><%= game.home_team.name %> <%= game.home_points %> : <%= game.away_points %> <%= game.away_team.name %> </h3>

  <h4><%= game.date.strftime("%m/%d/%Y") %></h4>
  <h4>Home: <%= Team.find_by(id: game.home_id).name %></h4>

  <table class="table table-hover table-condensed table-bordered">
    <thead class="thead-inverse">
      <tr class="active">
        <th>Date</th>
        <th>Number</th>
        <th>PTS</th>
        <th>FGM-FGA</th>
        <th>3PM-3PA</th>
        <th>FTM-FTA</th>
        <th>REB</th>
        <th>AST</th>
        <th>STL</th>
        <th>BLK</th>
      </tr>
    </thead>
  <% @total_pts = 0 %>
  <% @total_fgm = 0 %>
  <% @total_fga = 0 %>
  <% @total_tpm = 0 %>
  <% @total_tpa = 0 %>
  <% @total_ftm = 0 %>
  <% @total_fta = 0 %>
  <% @total_reb = 0 %>
  <% @total_ast = 0 %>
  <% @total_stl = 0 %>
  <% @total_blk = 0 %>

  <% game.performances.each do |performance| %>

    <tr>
      <% if Player.find_by(id: performance.player_id).team_id == game.home_id %>
      <td><%= Player.find_by(id: performance.player_id).name %></td>
      <td>#<%= Player.find_by(id: performance.player_id).player_number %></td>
      <td><%= performance.pts %></td>
      <td><%= performance.fgm %>-<%= performance.fga %></td>
      <td><%= performance.tpm %>-<%= performance.tpa %></td>
      <td><%= performance.ftm %>-<%= performance.fta %></td>
      <td><%= performance.reb %></td>
      <td><%= performance.ast %></td>
      <td><%= performance.stl %></td>
      <td><%= performance.blk %></td>
      <% @total_pts += performance.pts %>
      <% @total_fgm += performance.fgm %><% @total_fga += performance.fga %>
      <% @total_tpm += performance.tpm %><% @total_tpa += performance.tpa %>
      <% @total_ftm += performance.ftm %><% @total_fta += performance.fta %>
      <% @total_reb += performance.reb %>
      <% @total_ast += performance.ast %>
      <% @total_stl += performance.stl %>
      <% @total_blk += performance.blk %>
      <% end %>
    </tr>

<% end %>

    <thead>
      <tr class="active">
        <th>Totals</th>
        <th>-</th>
        <th><%= @total_pts %></th>
        <th><%= @total_fgm %>-<%= @total_fga %></th>
        <th><%= @total_tpm %>-<%= @total_tpa %></th>
        <th><%= @total_ftm %>-<%= @total_fta %></th>
        <th><%= @total_reb %></th>
        <th><%= @total_ast %></th>
        <th><%= @total_stl %></th>
        <th><%= @total_blk %></th>
      </tr>
    </thead>
  </table>

  <p>Away: <%= Team.find_by(id: game.away_id).name %></p>

  <table class="table table-hover table-condensed table-bordered">
  <thead>
    <tr class="active">
      <th>Name</th>
      <th>Number</th>
      <th>PTS</th>
      <th>FGM-FGA</th>
      <th>3PM-3PA</th>
      <th>FTM-FTA</th>
      <th>REB</th>
      <th>AST</th>
      <th>STL</th>
      <th>BLK</th>
    </tr>
  </thead>

  <% @total_pts = 0 %>
  <% @total_fgm = 0 %>
  <% @total_fga = 0 %>
  <% @total_tpm = 0 %>
  <% @total_tpa = 0 %>
  <% @total_ftm = 0 %>
  <% @total_fta = 0 %>
  <% @total_reb = 0 %>
  <% @total_ast = 0 %>
  <% @total_stl = 0 %>
  <% @total_blk = 0 %>
  <% game.performances.each do |performance| %>

    <tr>
      <% if Player.find_by(id: performance.player_id).team_id == game.away_id %>
      <td><%= Player.find_by(id: performance.player_id).name %></td>
      <td>#<%= Player.find_by(id: performance.player_id).player_number %></td>
      <td><%= performance.pts %></td>
      <td><%= performance.fgm %>-<%= performance.fga %></td>
      <td><%= performance.tpm %>-<%= performance.tpa %></td>
      <td><%= performance.ftm %>-<%= performance.fta %></td>
      <td><%= performance.reb %></td>
      <td><%= performance.ast %></td>
      <td><%= performance.stl %></td>
      <td><%= performance.blk %></td>
      <% @total_pts += performance.pts %>
      <% @total_fgm += performance.fgm %><% @total_fga += performance.fga %>
      <% @total_tpm += performance.tpm %><% @total_tpa += performance.tpa %>
      <% @total_ftm += performance.ftm %><% @total_fta += performance.fta %>
      <% @total_reb += performance.reb %>
      <% @total_ast += performance.ast %>
      <% @total_stl += performance.stl %>
      <% @total_blk += performance.blk %>
      <% end %>
    </tr>
  <% end %>
    <thead>
      <tr class="active">
        <th>Totals</th>
        <th>-</th>
        <th><%= @total_pts %></th>
        <th><%= @total_fgm %>-<%= @total_fga %></th>
        <th><%= @total_tpm %>-<%= @total_tpa %></th>
        <th><%= @total_ftm %>-<%= @total_fta %></th>
        <th><%= @total_reb %></th>
        <th><%= @total_ast %></th>
        <th><%= @total_stl %></th>
        <th><%= @total_blk %></th>
      </tr>
    </thead>
  </table>
<% end %>

x_league_app/app/views/players/show.html.erb
<h1><%= @player.name %> #<%= @player.player_number %> <%= Team.find_by(id: @player.team_id).name %></h1>

<% if current_user && current_user.admin %>
  <%= link_to "Edit", edit_player_path(@player.id) %>
  <%= link_to "Delete", player_path, method: :delete, data: { confirm: "Are you sure you want to delete this player and all of its performances?"} %>
<% end %>

  <h2>Season Stats</h2>
    <table class="table table-hover table-condensed table-bordered">
      <thead class="thead-inverse">
        <tr>
          <th>Date</th>
          <th>Opponent</th>
          <th>PTS</th>
          <th>FGM-FGA</th>
          <th>3PM-3PA</th>
          <th>FTM-FTA</th>
          <th>REB</th>
          <th>AST</th>
          <th>STL</th>
          <th>BLK</th>
          <% if current_user && current_user.admin %>
          <th></th>
          <% end %>
        </tr>
      </thead>

    <% @total_pts = 0 %>
    <% @total_fgm = 0 %>
    <% @total_fga = 0 %>
    <% @total_tpm = 0 %>
    <% @total_tpa = 0 %>
    <% @total_ftm = 0 %>
    <% @total_fta = 0 %>
    <% @total_reb = 0 %>
    <% @total_ast = 0 %>
    <% @total_stl = 0 %>
    <% @total_blk = 0 %>

  <% @performances = @player.performances %>
  <% @performances = @performances.sort_by {|p| p.game.date} %>
  <% @performances.each do |performance| %>

      <tr>
        <td><%= performance.game.date.strftime("%m/%d/%Y") %></td>
        <td>
          <% if performance.game.home_id == @player.team_id %>
          <% then %>
          <%= link_to Team.find_by(id: performance.game.away_id).name, team_path(Team.find_by(id: performance.game.away_id).id) %>
          <% else %>
          <%= link_to Team.find_by(id: performance.game.home_id).name, team_path(Team.find_by(id: performance.game.home_id).id) %>
          <% end %>
        </td>
        <td><%= performance.pts %></td>
        <td><%= performance.fgm %>-<%= performance.fga %></td>
        <td><%= performance.tpm %>-<%= performance.tpa %></td>
        <td><%= performance.ftm %>-<%= performance.fta %></td>
        <td><%= performance.reb %></td>
        <td><%= performance.ast %></td>
        <td><%= performance.stl %></td>
        <td><%= performance.blk %></td>
        <% if current_user && current_user.admin %>
        <td><%= link_to "Edit", edit_performance_path(performance.id) %></td>
        <% end %>
        <% @total_pts += performance.pts %>
        <% @total_fgm += performance.fgm %><% @total_fga += performance.fga %>
        <% @total_tpm += performance.tpm %><% @total_tpa += performance.tpa %>
        <% @total_ftm += performance.ftm %><% @total_fta += performance.fta %>
        <% @total_reb += performance.reb %>
        <% @total_ast += performance.ast %>
        <% @total_stl += performance.stl %>
        <% @total_blk += performance.blk %>
      </tr>
    <% end %>

    <tr>
      <td>Totals</td>
      <td>-</td>
      <td><%= @total_pts %></td>
      <td><%= @total_fgm %>-<%= @total_fga %></td>
      <td><%= @total_tpm %>-<%= @total_tpa %></td>
      <td><%= @total_ftm %>-<%= @total_fta %></td>
      <td><%= @total_reb %></td>
      <td><%= @total_ast %></td>
      <td><%= @total_stl %></td>
      <td><%= @total_blk %></td>
      <% if current_user && current_user.admin %>
      <td>-</td>
      <% end %>
    </tr>

    </table>

  <h2>Games</h2>

<% @games = @player.games %>
<% @games = @games.sort_by {|h| h[:date]} %>
<% @games.each do |game| %>

  <h3><%= link_to "#{game.away_team.name} #{game.away_points} : #{game.home_points} #{game.home_team.name}", game_path(game.id) %></h3>

  <h4>Home: <%= link_to Team.find_by(id: game.home_id).name, team_path(Team.find_by(id: game.home_id).id) %></h4>

  <table class="table table-hover table-condensed table-bordered">
    <thead class="thead-inverse">
      <tr>
        <th>Player</th>
        <th>Number</th>
        <th>PTS</th>
        <th>FGM-FGA</th>
        <th>3PM-3PA</th>
        <th>FTM-FTA</th>
        <th>REB</th>
        <th>AST</th>
        <th>STL</th>
        <th>BLK</th>
      </tr>
    </thead>
  <% @total_pts = 0 %>
  <% @total_fgm = 0 %>
  <% @total_fga = 0 %>
  <% @total_tpm = 0 %>
  <% @total_tpa = 0 %>
  <% @total_ftm = 0 %>
  <% @total_fta = 0 %>
  <% @total_reb = 0 %>
  <% @total_ast = 0 %>
  <% @total_stl = 0 %>
  <% @total_blk = 0 %>

  <% game.performances.each do |performance| %>

    <tr>
      <% if performance.player.team_id == game.home_id %>
      <td><%= link_to performance.player.name, player_path(performance.player.id) %></td>
      <td>#<%= performance.player.player_number %></td>
      <td><%= performance.pts %></td>
      <td><%= performance.fgm %>-<%= performance.fga %></td>
      <td><%= performance.tpm %>-<%= performance.tpa %></td>
      <td><%= performance.ftm %>-<%= performance.fta %></td>
      <td><%= performance.reb %></td>
      <td><%= performance.ast %></td>
      <td><%= performance.stl %></td>
      <td><%= performance.blk %></td>
      <% @total_pts += performance.pts %>
      <% @total_fgm += performance.fgm %><% @total_fga += performance.fga %>
      <% @total_tpm += performance.tpm %><% @total_tpa += performance.tpa %>
      <% @total_ftm += performance.ftm %><% @total_fta += performance.fta %>
      <% @total_reb += performance.reb %>
      <% @total_ast += performance.ast %>
      <% @total_stl += performance.stl %>
      <% @total_blk += performance.blk %>
      <% end %>
    </tr>

<% end %>

    <tr>
      <td>Totals</td>
      <td>-</td>
      <td><%= @total_pts %></td>
      <td><%= @total_fgm %>-<%= @total_fga %></td>
      <td><%= @total_tpm %>-<%= @total_tpa %></td>
      <td><%= @total_ftm %>-<%= @total_fta %></td>
      <td><%= @total_reb %></td>
      <td><%= @total_ast %></td>
      <td><%= @total_stl %></td>
      <td><%= @total_blk %></td>
    </tr>
  </table>

  <h4>Away: <%= link_to Team.find_by(id: game.away_id).name, team_path(Team.find_by(id: game.away_id).id) %></h4>

  <table class="table table-hover table-condensed table-bordered">
  <thead class="thead-inverse">
    <tr>
      <th>Player</th>
      <th>Number</th>
      <th>PTS</th>
      <th>FGM-FGA</th>
      <th>3PM-3PA</th>
      <th>FTM-FTA</th>
      <th>REB</th>
      <th>AST</th>
      <th>STL</th>
      <th>BLK</th>
    </tr>
  </thead>

  <% @total_pts = 0 %>
  <% @total_fgm = 0 %>
  <% @total_fga = 0 %>
  <% @total_tpm = 0 %>
  <% @total_tpa = 0 %>
  <% @total_ftm = 0 %>
  <% @total_fta = 0 %>
  <% @total_reb = 0 %>
  <% @total_ast = 0 %>
  <% @total_stl = 0 %>
  <% @total_blk = 0 %>
  <% game.performances.each do |performance| %>

    <tr>
      <% if performance.player.team_id == game.away_id %>
      <td><%= link_to performance.player.name, player_path(performance.player.id) %></td>
      <td>#<%= performance.player.player_number %></td>
      <td><%= performance.pts %></td>
      <td><%= performance.fgm %>-<%= performance.fga %></td>
      <td><%= performance.tpm %>-<%= performance.tpa %></td>
      <td><%= performance.ftm %>-<%= performance.fta %></td>
      <td><%= performance.reb %></td>
      <td><%= performance.ast %></td>
      <td><%= performance.stl %></td>
      <td><%= performance.blk %></td>
      <% @total_pts += performance.pts %>
      <% @total_fgm += performance.fgm %><% @total_fga += performance.fga %>
      <% @total_tpm += performance.tpm %><% @total_tpa += performance.tpa %>
      <% @total_ftm += performance.ftm %><% @total_fta += performance.fta %>
      <% @total_reb += performance.reb %>
      <% @total_ast += performance.ast %>
      <% @total_stl += performance.stl %>
      <% @total_blk += performance.blk %>
      <% end %>
    </tr>
  <% end %>
    <tr>
      <td>Totals</td>
      <td>-</td>
      <td><%= @total_pts %></td>
      <td><%= @total_fgm %>-<%= @total_fga %></td>
      <td><%= @total_tpm %>-<%= @total_tpa %></td>
      <td><%= @total_ftm %>-<%= @total_fta %></td>
      <td><%= @total_reb %></td>
      <td><%= @total_ast %></td>
      <td><%= @total_stl %></td>
      <td><%= @total_blk %></td>
    </tr>
  </table>
<% end %>

x_league_app/app/views/users/index.html.erb
<% if current_user %>

<h2>Welcome, <%= current_user.name %></h2>

<p>Favorite a <%= link_to "player", players_path %> to make it your home page.</p>

<% else %>

<h2>Welcome to X League's Statistics Web App</h2>

<p><%= link_to "Log in", login_path %> to select a favorite <%= link_to "player", players_path %> and make it your home page. </p>
<% end %>

<% if current_user && current_user.admin %>
  <%= link_to "Create a Team", new_team_path %> ||
  <%= link_to "Create a Player", new_player_path %> ||
  <%= link_to "Create a Game", new_game_path %> ||
  <%= link_to "Create a Performance", new_performance_path %>
<% end %>